plugins {
    id "com.android.application"
}

android {
    namespace "uk.co.swenlink.books"
    compileSdk 35

    defaultConfig {
        applicationId "uk.co.swenlink.books"
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName "1.0.0"
    }
}

dependencies {
    implementation "com.google.androidbrowserhelper:androidbrowserhelper:2.5.0"
}
